#+TITLE: Curvature of Surfaces
#+OPTIONS: toc:nil num:nil

* Second Derivatives
** Second Derivatives
** Connection

For a vector field \(Z \in \Gamma(TS)\) define the \(C^{\infty}(S \to \RR)\)-linear map
\[
\nabla Z : Y \in \Gamma(TS) \mapsto \nabla_Y Z \in \Gamma(TS)
\]

This is analogous to the differential \(df\)

The second derivative of \(Z\) should be...?

** Second Covariant Derivative

#+BEGIN_env defn
Let \(Z \in \Gamma(TS)\) be a vector field. The second covariant derivative of \(Z\) is defined to be the covariant derivative of \(T = \nabla Z\)
\begin{equation*}
\begin{split}
[\nabla_X (\nabla Z)] (Y) &= \nabla_X[\nabla Z (Y)] - \nabla Z [\nabla_X Y] \\
&= \nabla_X(\nabla_Y Z) - \nabla_{\nabla_X Y} Z.
\end{split}
\end{equation*}
#+END_env

** Second Covariant Derivative

We also write \(\nabla^2 Z (X, Y)\) or \(\nabla^2_{X, Y} Z\) for \((\nabla_X (\nabla Z)) (Y)\)

Sometimes people also write
\[
\nabla_X \nabla_Y Z
\]
but we won't since this could be confused with \(\nabla_X (\nabla_Y Z) \neq \nabla^2 Z (X, Y)\).

** Example

#+BEGIN_env eg
Polar coords \(r, \theta\) with coordinate fields \(R, T\):
\[
D_R R = 0, \quad D_T T = -r R, \quad D_T R = D_R T = \frac{1}{r} T.
\]

\begin{equation*}
\begin{split}
D^2 T (R, T) &= D_R (D_T T) - D_{D_R T} T \\
&= D_R (-r R) - D_{r^{-1} T} T \\
&= -r D_R R - (D_R r) R - r^{-1} D_T T \\
&= - (D_R r) R + R \\
&= 0
\end{split}
\end{equation*}
#+END_env

* Curvature Tensor
** Curvature Tensor
** Second Commutator

\begin{equation*}
\begin{split}
\nabla^2 Z (X, Y) - &\nabla^2 Z(Y, X) = \left[\nabla_X (\nabla_Y Z) - \nabla_{\nabla_X Y} Z\right] \\
&\quad - \left[\nabla_Y (\nabla_X Z) - \nabla_{\nabla_Y Z} Z\right] \\
&= \nabla_X (\nabla_Y Z) - \nabla_Y (\nabla_X Z) - \nabla_{\nabla_X Y - \nabla_Y X} Z \\
&= \nabla_X (\nabla_Y Z) - \nabla_Y (\nabla_X Z) - \nabla_{[X, Y]} Z.
\end{split}
\end{equation*}

Even if \([X, Y] = 0\) we may still have \(\nabla^2 Z (X, Y) - \nabla^2 Z(Y, X) \neq 0\).

** The Curvature Tensor

#+BEGIN_env defn
The /curvature tensor/ is the commutator of second derivatives,
\begin{equation*}
\begin{split}
\Rm(X, Y) Z &= \nabla^2 Z (X, Y) - \nabla^2 Z (Y, X) \\
&= \nabla_X (\nabla_Y Z) - \nabla_Y(\nabla_X Z) - \nabla_{[X, Y]} Z.
\end{split}
\end{equation*}
#+END_env

The \([X, Y]\) term acounts for \(\nabla_X Y, \nabla_Y X\) in the second derivatives. It also compensates non-commuting \(X, Y\) .

** Curvature Tensor is Pointwise

#+BEGIN_env thm
For \(p \in S\), \([\Rm(X, Y) Z](p)\) only depends on \(X(p), Y(p), Z(p)\).
#+END_env

Note that \(\Rm(X, Y) Z\) involves derivatives \(\nabla X(p), \nabla Y(p), \nabla Z(p), \nabla^2 Z(p)\).

All these cancel out!

** Curvature Tensor is Pointwise

#+BEGIN_env pf
\begin{align*}
\nabla_X (\nabla_Y Z) &= X^i \partial_i Y^j \nabla_j Z + X^i Y^j \nabla_i(\nabla_j Z) \\
-\nabla_Y (\nabla_X Z) &= -Y^i \partial_i X^j \nabla_j Z + Y^i X^j \nabla_i(\nabla_j Z) \\
-\nabla_{[X, Y]} Z &= -X^i \partial_i Y^j \nabla_j Z + Y^i \partial_i X^j \nabla_j Z
\end{align*}

\[
\Rm(X, Y) Z = X^i Y^j[\nabla_i (\nabla_j Z) - \nabla_j (\nabla_i Z)]
\]
#+END_env

** Curvature Tensor is Pointwise

#+BEGIN_env pf
\[
\Rm(X, Y) Z = X^i Y^j[\nabla_i (\nabla_j Z) - \nabla_j (\nabla_i Z)]
\]

\begin{equation*}
\begin{split}
\nabla_i (\nabla_j Z) &= \partial_i \partial_j Z^k \partial_k + \partial_j Z^k \nabla_i \partial_k + \partial_i Z^k \nabla_j \partial_k \\
&\quad + Z^k \nabla_i(\nabla_j \partial_k) \\
&= A_{ij} + Z^k \nabla_i(\nabla_j \partial_k)
\end{split}
\end{equation*}

Here \(A_{ij} = A_{ji}\).
#+END_env

** Curvature Tensor is Pointwise

#+BEGIN_env pf
\begin{equation*}
\begin{split}
\nabla_i (\nabla_j Z) - \nabla_j (\nabla_i Z) &= A_{ij} - A_{ji} \\
&\quad + Z^k [\nabla_i (\nabla_j \partial_k) - \nabla_j (\nabla_i \partial_k)] \\
&= Z^k \Rm(T_i, T_j) \partial_k
\end{split}
\end{equation*}

\[
[\Rm(X, Y) Z](p) = X^i(p) Y^i(p) Z^k(p) [\Rm(T_i, T_j) \partial_k] (p).
\]
#+END_env

** Curvature Tensor Notation

\[
\Rm(X, Y) Z = X^i Y^j Z^k R_{ijk}^{\ell} \partial_{\ell}
\]
\[
R_{ijk}^{\ell} \partial_{\ell} = \Rm(\partial_i, \partial_j) \partial_k
\]

\(R_{ijk}^{\ell}\) is the \(\partial_{\ell}\) component of \(\Rm(\partial_i, \partial_j) \partial_j\)

Common alternate notation: \(R_{ijk}^{\ell} \partial_{\ell} = \Rm(\partial_j, \partial_i) \partial_k\)

* Euclidean Curvature Tensor
** Euclidean Curvature Tensor
** Euclidean Curvature Tensor

#+BEGIN_env eg
In \(\RR^2\) with the Euclidean covariant derivative \(D\)
\[
\Rm (X, Y) Z = 0
\]
since \(D_i \partial_j = 0\) for every \(i,j\).
#+END_env

* Spherical Curvature Tensor
** Spherical Curvature Tensor
** Spherical Curvature Tensor

#+BEGIN_env eg
\(F(\theta, \varphi) = (\sin\varphi \cos\theta, \sin\varphi \sin\theta, \cos\varphi)\)

\(T = dF(\partial_{\theta}) \quad P = dF(\partial_{\varphi})\)

\(\Rm(T, P) T = -\sin^2\varphi P\)

\(\Rm\left(\frac{T}{\abs{T}}, \frac{P}{\abs{P}}\right) \frac{T}{\abs{T}} = -P\)

\(g\left(\Rm\left(\frac{T}{\abs{T}}, \frac{P}{\abs{P}}\right) \frac{T}{\abs{T}}, \frac{P}{|P|}\right) = -1\)
#+END_env

** Spherical Curvature Tensor

#+BEGIN_env ex
\begin{align*}
\nabla_T T &= -\sin\varphi\cos\varphi P \\
\nabla_P P &= 0 \\
\nabla_T P = \nabla_P T &= \cot\varphi T \\
[T, P] &= 0
\end{align*}

Thus
\[
\Rm(T, P) T = \nabla_T (\nabla_P T) - \nabla_P (\nabla_T T)
\]
#+END_env

** Spherical Curvature Tensor

#+BEGIN_env eg
\begin{equation*}
\begin{split}
\nabla_T (\nabla_P T) &= \nabla_T (\cot \varphi T) \\
&= \cot\varphi \nabla_T T = -\cos^2 \varphi P \\
\nabla_P (\nabla_T T) &= \nabla_P (-\sin\varphi\cos\varphi P) \\
&= - \partial_P(\sin\varphi\cos\varphi P) P \\
&= -(\cos^2\varphi - \sin^2\varphi) P
\end{split}
\end{equation*}

\[
\Rm(T, P) T = -\sin^2 \varphi P
\]
#+END_env

