#+TITLE: Surface Geometry
#+OPTIONS: toc:nil num:nil

* Riemannian Metric
** Riemannian Metric

The Riemannian metric of a surface completely determines the geometry of the surface.

** Metric (First Fundamental Form)

#+BEGIN_env defn
The (Riemmanian) metric \(g\) on \(S\) is the inner product \(g_p\) at each point \(p \in S\) defined for tangent vectors \(V, W \in T_p S \subseteq \RR^3\) by
\[
g_p(V, W) = \ip{V}{V}_{\RR^3}.
\]
#+END_env

** Coordinate Expression of Metric

\[
V = c^1 \partial_{x_1} \varphi + c^2 \partial_{x_2} \varphi, \quad W = d^1 \partial_{x_1} \varphi + d^2 \partial_{x_2} \varphi
\]

\begin{equation*}
\begin{split}
g(V, W) &= \ip{c_1 \frac{\partial \varphi}{\partial x_1} + c_2 \frac{\partial \varphi}{\partial x_2}}{d_1 \frac{\partial \varphi}{\partial x_1} + d_2 \frac{\partial \varphi}{\partial x_2}} \\
&= c_1 d_1 \ip{\frac{\partial \varphi}{\partial x_1}}{\frac{\partial \varphi}{\partial x_1}} + c_2 d_2 \ip{\frac{\partial \varphi}{\partial x_2}}{\frac{\partial \varphi}{\partial x_2}} \\
&\quad + (c_1d_2 + c_2 d_1) \ip{\frac{\partial \varphi}{\partial x_1}}{\frac{\partial \varphi}{\partial x_2}} \\
&= c_1 d_1 g_{11} + c_2 d_2 g_{22} + (c_1 d_2 + c_2 d_1) g_{12}.
\end{split}
\end{equation*}

** Matrix Form in Local Coordinates

\begin{equation*}
g = \begin{pmatrix}
g_{11} & g_{12} \\
g_{21} & g_{22}
\end{pmatrix}
:=
\begin{pmatrix}
\ip{\frac{\partial \varphi}{\partial x_1}}{\frac{\partial \varphi}{\partial x_1}} &  \ip{\frac{\partial \varphi}{\partial x_1}}{\frac{\partial \varphi}{\partial x_2}} \\
\ip{\frac{\partial \varphi}{\partial x_2}}{\frac{\partial \varphi}{\partial x_1}} & \ip{\frac{\partial \varphi}{\partial x_2}}{\frac{\partial \varphi}{\partial x_2}}
\end{pmatrix}
\end{equation*}

\((g_{ij})\) is /positive definite/ and /symmetric/.

** Change of Coordinates

Change of coords \(\tau = \varphi^{-1} \circ \psi: \RR^2 \to \RR^2\):
\begin{equation*}.
\begin{split}
g^{\psi}_{ab} &= g^{\varphi \circ \tau}_{ab} \\
&= \ip{\partial_{y^a} (\varphi \circ \tau)}{\partial_{y^b} (\varphi \circ \tau)} \\
&= \ip{\sum_i \partial_{x^i} \varphi \partial_{y^a} \tau^i}{\sum_j \partial_{x^j} \varphi \partial_{y^b} \tau^j} \\
&= \sum_{ij} g_{ij} \partial_{y^a} \tau^i \partial_{y^b} \tau^j
\end{split}
\end{equation*}

** Matrix Change of Coordinates

\begin{equation*}
\begin{split}
g^{\varphi \circ \tau}(X, Y) &= \ip{d(\varphi \circ \tau) \cdot X}{d(\varphi \circ \tau) \cdot Y} \\
&= \ip{d\varphi(d\tau \cdot X)}{d\varphi(d\tau \cdot y)} \\
&= g^{\varphi} (d\tau \cdot X, d\tau \cdot Y).
\end{split}
\end{equation*}

* Examples
** Examples
** Euclidean Metric

#+BEGIN_env eg

#+END_env

** Spherical Metric

#+BEGIN_env eg

#+END_env

** Paraboloid

#+BEGIN_env eg

#+END_env

* Angle and Length
** Angle and Length

We can define angle and length by using the metric \(g\).

** Cauchy Schwartz Inequality

#+BEGIN_lemma
\[
\abs{g(X, Y)} \leq \abs{X}\abs{Y}.
\]
#+END_lemma

See https://en.wikipedia.org/wiki/Cauchy%E2%80%93Schwarz_inequality#First_proof

Rearranging Cauchy-Schwarz inequality for \(X, Y \ne 0\) gives
\[
\frac{g(X, Y)}{\abs{X}\abs{Y}} \in [-1, 1]
\]
and \(\theta\) is well defined after choosing an inverse such as \(\theta \in [0, \pi]\).

** Length and Angle of Tangent Vectors

#+BEGIN_env defn
Let \(X\) be a tangent vector. Then it's length is defined to be
\[
\abs{X}_g := \sqrt{g(X, X)}.
\]
#+END_env

#+BEGIN_env defn
The angle, \(\theta\) between two tangent vectors \(X, Y\) (at the same point \(x \in S\)!) is defined by
\[
\cos \theta = \frac{g(X, Y)}{\abs{X}\abs{Y}} = g\left(\frac{X}{\abs{X}}, \frac{Y}{\abs{Y}}\right).
\]
#+END_env

** Arc Length

#+BEGIN_defn
Let \(\gamma : (a, b) \to S\) be a smooth curve. The /arc-length/ of \(\gamma\) is
\[
L(\gamma) = \int_a^b \abs{\gamma'(t)} dt = \int_a^b \sqrt{g_{\gamma(t)} (\gamma'(t), \gamma'(t))} dt.
\]
#+END_defn

This is just the arc-length in \(\RR^3\) but expressed in terms of \(g\).

** Example: Sphere
* Area
** Area

Area is also determined by the metric.

** Area

Let
\[
X_u = d\varphi (e_u) = \partial_u \varphi, \quad X_v = d\varphi (e_v) = \partial_v \varphi
\]
be coordinate vectors.

Since \(d\varphi\) is injective, \(X_u, X_v\) form a basis for \(T_x M\).

** Area

\(X_u, X_v\) determines a parallelogram \(X_u \wedge X_v \subseteq T_x M\).

Taking a small rectangle \(R = \{(u, v) \in (u_0, u_0 + \Delta u) \times (v_0, v_0 + \Delta v)\}\), we approximate the area of \(\varphi(R) \subseteq S\) by
\[
\text{Area} (\varphi(S)) \simeq \text{Area} (X_u \wedge X_v) = \abs{X_u \times X_v} \text{Area}(R) = \abs{X_u \times X_v} \Delta u \Delta v.
\]

** Area

Note that \(\abs{X_u \times X_v}^2 = \det \lambda^T \lambda = \det g\) where \(\lambda = (X_u \quad X_v)\)!

Area is the limit of a Riemann sum: for any region \(\Omega = \varphi(W) \subseteq \varphi(U)\)
\[
\text{Area} (\Omega) = \int_W \sqrt{\det g(u, v)} du dv.
\]

** Archimedes Cylinder to Sphere
