#+TITLE: Surfaces
#+OPTIONS: toc:nil num:nil

* Graphs of functions
** The graph of a function

#+BEGIN_env defn
Let \(f : U \subseteq_{\text{open}} \RR^2 \to \RR\) be smooth function
\[
\graph f := \{(u, v, f(u, v)) : (u, v) \in U\} \subseteq \RR^3.
\]
#+END_env

** Parametrisation

\[
F(u, v) = (u, v, f(u, v))
\]
is a /parmetrisation/ of \(\graph f\).

\(F\) gives a one to one identification of the points \((x, y, z) \in \graph f\) with the points \((u, v) \in U\) an open set of \(\RR^2\) on which we can do calculus!

** Paraboloid

#+BEGIN_env eg
Let \(f (u, v) = u^2 + v^2\)

\[
\graph(f) = (u, v, u^2 + v^2)
\]
#+END_env

** Smooth functions on a graph

#+BEGIN_env defn
A function \(\eta : \graph f \to \RR\) is smooth if the function

\(\eta \circ F (x, y) = \eta(x, y, f(x, y))\) is smooth.

A function \(\eta = (\eta^1, \dots, \eta^m) : \graph f \to \RR^m\) is smooth if each \(\eta^i\) is.
#+END_env

** Ambient Smooth Functions

If \(\bar{\eta} : \RR^3 \to \RR\) is smooth then, by the chain rule \(\eta := \bar{\eta}|_{\graph f}\) is smooth since
\[
\eta \circ F = \bar{\eta}\lvert_{\graph f} \circ F = \bar{\eta} \circ F
\]
is the composition of smooth functions.

** Extension of smooth functions

#+BEGIN_env lem
Let \(\eta : \graph f \to \RR\) be a smooth function. Then /locally/ there exists a smooth function \(\bar{\eta} : \RR^3 \to \RR\) such that \(\eta = \bar{\eta}\lvert_{\graph f}\)
#+END_env

** Proof - Inclusions

In the special case that \(f \equiv 0\):

\(F(u, v) = (u, v, 0)\) is an inclusion.

By assumption \(\eta \circ F (u, v) = \eta(u, v, 0)\) is smooth.

Define \(\bar{\eta}(x, y, z) = \eta \circ \pi (x, y, z) = \eta(x, y, 0)\).

** Proof - General Case

\(F\) is an immersion: \(F = \psi^{-1} \circ \iota \circ \varphi\)

\(\psi(\graph(f)) = \lbrace z=0 \rbrace\)

\(\mu = \eta \circ \psi^{-1} \circ \iota = \eta \circ F \circ \varphi^{-1}\) is smooth on \(\lbrace z = 0 \rbrace\)

\(\bar{\eta} = \bar{\mu} \circ \psi\)

* Regular Surfaces
** Graphs are not enough

- Graphs are /global/ surfaces. They are diffeomorphic to an open set in the plane.
- Many surfaces are not diffeomorphic to an open set in the plane!
- The sphere, a torus, etc.

** Graphs are not enough

#+BEGIN_export html
{% include img_slides.html file="docarmo_cover.jpg" %}
#+END_export

** Definition of Regular Surface

#+BEGIN_env defn
A regular surface, \(S \subseteq \RR^3\) is covered by smooth /local parametrisations/ \(\varphi_{\alpha} : U_{\alpha} \subseteq \RR^2 \to \RR^3\) such that

1. \(S = \cup_{\alpha} V_{\alpha}\) where \(V_{\alpha} = \varphi_{\alpha}(U_{\alpha})\) is open in \(S\)
2. \(\varphi_{\alpha}\) is a homeomorphism \(U_{\alpha} \to V_{\alpha}\)
3. \(d\varphi_{\alpha}|_x : \RR^2 \to \RR^3\) is injective for each \(x \in U_{\alpha}\)
#+END_env

** Regular Surface

#+BEGIN_export html
{% include img_slides.html file="regular_surface.png" %}
#+END_export

** Induced Topology

- \(V \subset S\) is /open/ if and only if \(V = S \cap W\) for \(W \subseteq \RR^3\) open

- Continuity of the map
  \[
  \varphi_{\alpha}^{-1} : V_{\alpha} \subseteq S \subseteq \RR^3 \to U_{\alpha} \subseteq \RR^2
  \]

  means for all convergent sequences \((x_n) \subseteq V_{\alpha}\), we have
  \[
  \lim_{n \to \infty} \varphi_{\alpha}^{-1} (x_n) = \varphi_{\alpha}^{-1} (\lim_{n\to\infty} x_n).
  \]

* Examples
** Example: Graphs

- There is just one parametrisation:
   \[
   \varphi : (u, v) \mapsto (u, v, f(u, v))
   \]

- Inverse \(\varphi^{-1} = \pi_{z=0}\)
- \[
  d\varphi = \begin{pmatrix}
  1 & 0 \\
  0 & 1 \\
  \partial_u f & \partial_v f
  \end{pmatrix}
  \]

** Example The Unit Sphere

The sphere is not a graph over any plane \(P \subseteq \RR^3\)

- Let \(N\) be the normal to \(P\). Then for any point \(p \in P\), the line \(p + t N\) either intersects in exactly 2 distinct points, 1 point or no points.
- Substitute: \(p + t N\) into \(x^2 + y^2 + z^2 = 1\) and you get a quadratic in \(t\).
- Provided \(p + t N\) is not tangent to the sphere (multiplicity $2$ root), the quadratic has either $0$ roots or $2$ roots.

** Hemisphere Parametrisation

#+BEGIN_export html
{% include img_slides.html file="docarmo_cover.jpg" %}
#+END_export

** Hemisphere Parametrisation: North-South

Let \(U = \{u^2 + v^2 < 1\}\) be the unit disc.

- Northern hemisphere (over \(z = 0\) plane)
  \[
  \varphi_N (u,v) = \left(u, v, \sqrt{1 - (u^2 + v^2)}\right)
  \]

- Southern hemisphere (over \(z = 0\) plane)
  \[
  \varphi_S (u,v) = \left(u, v, -\sqrt{1 - (u^2 + v^2)}\right)
  \]

** Hemisphere Parametrisation: East-West

Let \(U = \{u^2 + v^2 < 1\}\) be the unit disc.

- Eastern hemisphere (over \(y = 0\) plane)
  \[
  \varphi_E (u, v) = \left(u, \sqrt{1 - (u^2 + v^2)}, v\right)
  \]

- Western hemisphere (over \(y = 0\) plane)
  \[
  \varphi_W (u, v) = \left(u, -\sqrt{1 - (u^2 + v^2)}, v\right)
  \]

** Hemisphere Parametrisation: Front-Back

Let \(U = \{u^2 + v^2 < 1\}\) be the unit disc.

- Front hemisphere (over \(x = 0\) plane)
  \[
  \varphi_E (u, v) = \left(\sqrt{1 - (u^2 + v^2)}, u, v\right)
  \]

- Back hemisphere (over \(x = 0\) plane)
  \[
  \varphi_W (u, v) = \left(-\sqrt{1 - (u^2 + v^2)}, u, v\right)
  \]

** Polar Coordinates

For \((\theta, \phi) \in (0, 2\pi) \times (0, \pi)\), define
\[
\varphi (\theta, \phi) = (\sin \phi \cos \theta, \sin \phi \sin \theta, \cos \phi)
\]

Then \(\varphi\) covers all of the sphere except for the semi-circle \(\{x \geq 0\} \cap \{y = 0\} \cap \SS^2\). 

We cover the entire sphere by also using the parametrisation
\[
\psi (\theta, \phi) = (\sin \phi \cos \theta, \cos\phi, \sin \phi \sin \theta)
\]

** Example: Torus

#+BEGIN_export html
{% include img_slides.html file="torus.png" %}
#+END_export

** Torus

- \(xz\)-plane circle \((x, y, z) = (a \cos \theta + b, 0, a \sin \theta)\)
- Here \(a < b\). Rotate around the \(z\)-axis. 
- The rotation is
  \[
  (x, z) \mapsto (x \cos \phi, x \sin \phi, z)
  \]

- Thus our parametrisation is
  \[
  (a \cos\phi \cos \theta + b \cos\phi, a \sin \phi \cos \theta + b \sin \phi, a \sin \theta).
  \]

* Change of Parameters
** Change of Parameters

#+BEGIN_export html
{% include img_slides.html file="regular_surface_change_of_params.png" %}
#+END_export

** Change of Parameters

By the Inverse Function Theorem
\[
\tau_{\alpha\beta} = \varphi_{\beta}^{-1} \circ \varphi_{\alpha} : \varphi_{\alpha}^{-1} (V_{\beta}) \subseteq \RR^2 \to \varphi_{\beta}^{-1} (V_{\alpha}) \subseteq \RR^2
\]
is a *diffeomorphism*.

\(\tau_{\alpha\beta}\) is smooth with a smooth inverse  \(\tau_{\beta\alpha}\).

We could replace condition 3 that \(d\varphi_{\alpha}\) is injective with the condition that \(\tau_{\alpha\beta}\) is smooth.

** Diffeomorphism Invariance
\[
\Phi_{\alpha\beta} : f \in C^{\infty}(\varphi_{\beta}^{-1} (V_{\alpha}), \RR) \mapsto f \circ \tau_{\alpha\beta} \in C^{\infty}(\varphi_{\alpha}^{-1} (V_{\beta}), \RR)
\]
is a bijection.

$\Phi_{\alpha\beta}$ establishes a one-to-one correspondence of smooth functions in one parametrisation with smooth functions in another parametrisation. 

A function \(f : \varphi_{\beta}^{-1} (V_{\alpha}) \to \RR\) is differentiable if and only if \(f \circ \tau_{\alpha\beta} : \varphi_{\alpha}^{-1} (V_{\beta}) \to \RR\) is differentiable.

** Diffeomorphism

#+BEGIN_env thm
Let \(S\) be a regular surface with local parametrisations
\[
\varphi_{\alpha} : U_{\alpha} \to V_{\alpha} \subseteq S \subseteq \RR^3
\]
Then for each \(\alpha, \beta\) with \(V_{\alpha} \cap V_{\beta} \neq \emptyset\), \(\tau_{\alpha\beta}\) is smooth.

Moreover, \(\tau_{\alpha\beta}\) is invertible with inverse \(\tau_{\beta\alpha}\) hence is a diffeomorphism.
#+END_env

** Proof Idea

*Idea*: \(\tau_{\alpha\beta} = \varphi_{\beta}^{-1} \circ \varphi_{\alpha}\) is the composition of smooth functions.

*Problem*: What does it mean for \(\varphi_{\beta}^{-1}\) to be smooth?

*Solution*: Locally \(\varphi_{\beta}^{-1} = \Phi_{\beta}^{-1}|_S\) for \(\Phi_{\beta}^{-1} : \RR^3 \to \RR^3\) smooth.

** Proof

Apply the Inverse Function Theorem:

\[
\Phi_{\beta} (u, v, w) = \varphi_{\beta} (u, v) + w e_i
\]

\[
\Phi_{\beta}|_{w=0} = \varphi_{\beta}
\]

\begin{equation*}
d\Phi_{\beta} = \begin{pmatrix}
\large{d\varphi} & e_i
\end{pmatrix}
\end{equation*}

