#+OPTIONS: toc:nil num:nil
#+BEGIN_export html
---
title: Surfaces
short_title: Surfaces
---
#+END_export

#+LaTeX_class: article_no_macros
#+LaTeX_Header: \usepackage{pabnotes}
#+LaTeX_Header: \newcommand{\weeknum}{04}
#+LaTeX_Header: \newcommand{\topic}{Surfaces}

#+BEGIN_export html
<ul>
<li><a href="{{ '/slides/surfaces' | relative_url }}" target="_blank">Surfaces Slides</a></li>
<li><a href="{{ '/slides/surface_tangent_space' | relative_url }}" target="_blank">Tangent Space Slides</a></li>
<li><a href="{{ '/pdf/surfaces.pdf' | relative_url }}" target="_blank">Surfaces PDF Notes</a></li>
</ul>
#+END_export

* Graphs

#+BEGIN_env defn
Let \(f : U \subseteq_{\text{open}} \RR^2 \to \RR\) be smooth function. The graph, \(\graph f\) is the set,
\[
\graph f := \{(u, v, f(u, v)) : (u, v) \in U\} \subseteq \RR^3.
\]
#+END_env

The function \(F : U \to \RR^3\) defined by
\[
F(u, v) = (u, v, f(u, v))
\]
is a /parmetrisation/ of \(\graph f\).

Observe that \(F\) gives a one to one identification of the points \((x, y, z) \in \graph f\) with the points \((u, v) \in U\) an open set of \(\RR^2\) on which we can do calculus! As a map \(F : U \to \graph(f)\), the inverse is \(F^{-1} = \pi|_{\graph(f)} : \graph(f) \to U\)
\[
F^{-1} : (x, y, z) \in \graph(f) \mapsto (x, y).
\]

#+BEGIN_env eg :title "Paraboloid"
Consider the paraboloid,
\[
S = \lbrace (x, y, z) : z = x^2 + y^2 \rbrace.
\]
Let \(f (u, v) = u^2 + v^2\) in which case,
\[
\graph(f) = (u, v, u^2 + v^2) = S
\]
and a parametrisation is
\[
F(u, v) = (u, v, u^2 + v^2).
\]
#+END_env

In general, we can't differentiate a function \(\eta : \graph(f) \to \RR\), for if \(p \in \graph(f)\) the definition of derivative gives
\[
\partial_X \eta (p) = \lim_{h \to 0} \frac{\eta(p + hX) - \eta(p)}{h}.
\]
In general \(p + h X \notin \graph{f}\), in which case the difference quotient is not even defined let alone the limit.

For example, let \(p = (1, 0, 1)\) be a point on the paraboloid and let \(X = e_1 = (1, 0, 0)\). Then for any \(h\),
\[
p + hX = (1 + h, 0, 1)
\]
This is not a point on the parabolid \(z = x^2 + y^2\) and hence \(\eta(p + hX)\) is not defined if \(\eta\) is defined only on the graph.

So we need to another way to define smooth functions. We do this via our parametrisation.

#+BEGIN_env defn
A function \(\eta : \graph f \to \RR\) is smooth if the function

\(\eta \circ F (x, y) = \eta(x, y, f(x, y))\) is smooth.

A function \(\eta = (\eta^1, \dots, \eta^m) : \graph f \to \RR^m\) is smooth if each \(\eta^i\) is.
#+END_env

In the case that we start with a smooth function on the ambient space, then restircting to \(\graph(f)\) is smooth. That is, if \(\bar{\eta} : \RR^3 \to \RR\) is smooth then, by the chain rule \(\eta := \bar{\eta}|_{\graph f}\) is smooth since
\[
\eta \circ F = \bar{\eta}\lvert_{\graph f} \circ F = \bar{\eta} \circ F
\]
is the composition of smooth functions.

In fact, all smooth functions arise this way. Here's the local version of that statement.

#+BEGIN_env lem
Let \(\eta : \graph f \to \RR\) be a smooth function. Then /locally/ there exists a smooth function \(\bar{\eta} : \RR^3 \to \RR\) such that \(\eta = \bar{\eta}\lvert_{\graph f}\).
#+END_env

#+BEGIN_env pf :title "Special case - Immersions"
In the special case that \(f \equiv 0\),
\[
F(u, v) = (u, v, 0)
\]
is an inclusion. By assumption \(\eta \circ F (u, v) = \eta(u, v, 0)\) is smooth. Define
\[
\bar{\eta}(x, y, z) = \eta \circ \pi (x, y, z) = \eta(x, y, 0)
\]
which is then smooth.
#+END_env

Thus extending smooth maps on inclusions into coordinate planes is straightforward. The general case follows by the Immersion Theorem which says that a surface is locally a coordinate plane up to diffeomorphism.

#+BEGIN_env pf :title "General Case"
\(F\) is an immersion, hence by the Immersion Theorem there are local diffeomorphisms such that \(F = \psi^{-1} \circ \iota \circ \varphi\). Since \(\psi \circ F = \iota \circ \varphi\) we get that \(\psi(\graph(f)) \subseteq \Img \iota = \lbrace z=0 \rbrace\).

We can (locally) define a new smooth function \(\mu : \lbrace z = 0 \rbrace \to \RR\) by
\[
\mu = \eta \circ \psi^{-1}.
\]
Then
\begin{equation*}
\begin{split}
\eta \circ F &= \eta \circ \psi^{-1} \circ \iota \circ \varphi \\
&= \mu \circ \iota \circ \varphi
\end{split}
\end{equation*}
is smooth since \(\eta \circ F\) is smooth by assumption. Thus
\[
\mu \circ \iota = \eta \circ F \circ \varphi^{-1}
\]
is smooth. Using the fact that \(\iota \circ \pi\) is the identity on \(\{z=0\}\) where \(\pi : \RR^3 \to \RR^2\) is the projection \((x, y, z) \mapsto (x, y)\) we get
\[
\mu = \mu \circ \iota \circ \pi = (\eta \circ F) \circ \varphi^{-1} \circ \pi
\]
is smooth.

Then we let \(\bar{\mu}\) be a smooth extension of \(\mu\) and let
\[
\bar{\eta} = \bar{\mu} \circ \psi^{-1}
\]
which is smooth. Moreover, since \(\bar{\mu}|_{z=0} = \mu\),
\begin{equation*}
\begin{split}
\bar{\eta}|_{\graph(f)} &= (\bar{\mu} \circ \psi^{-1})|_{\graph(f)} \\
&= \bar{\mu}|_{z=0} \circ \psi^{-1}_{\graph(f)} \\
&= (\mu \circ \psi^{-1})|_{\graph(f)} \\
&= \eta
\end{split}
\end{equation*}
and we obtain a local, smooth extension as required.
#+END_env

* Regular Surfaces

Graphs are /global/ surfaces. They are diffeomorphic to an open set in the plane. Many surfaces are not diffeomorphic to an open set in the plane! For example, none of the sphere, torus, cylinder are diffeomorphic to the plane. The proof requires some topology so we won't discuss it here. It's just mentioned to show that the study of regular surfaces requires us to consider more than just graphs - we must widen our definition!

#+BEGIN_env defn
A regular surface, \(S \subseteq \RR^3\) is a set covered by smooth /local parametrisations/ \(\varphi_{\alpha} : U_{\alpha} \subseteq \RR^2 \to \RR^3\) such that

1. \(S = \cup_{\alpha} V_{\alpha}\) where \(V_{\alpha} = \varphi_{\alpha}(U_{\alpha})\) is open in \(S\)
2. \(\varphi_{\alpha}\) is a homeomorphism \(U_{\alpha} \to V_{\alpha}\)
3. \(d\varphi_{\alpha}|_x : \RR^2 \to \RR^3\) is injective for each \(x \in U_{\alpha}\)
#+END_env

#+BEGIN_export html
{% include img.html file="regular_surface.png" %}
#+END_export

We say that a regular surface is /locally/ diffeomorphic to \(\RR^2\). Each of the local parametrisations gives a one-to-one, smooth correspondence of part of \(S\) and an open subset in \(\RR^2\). The first condition in the definition says that every part of \(S\) is in such correspondence. The second condition says that the correspondence is continuous (both ways!) and hence for topological considerations (such as openness, continuity etc.), a regular surface is locally equivalent to \(\RR^2\). Of course, we must at least require the local parametrisations are smooth (we are doing calculus after all). The third condition goes further and the condition that allows us to locally identity \(S\) with an open set in \(\RR^2\) is a *smooth way*. This allows us to define a natural notion of calculus on \(S\), by taking our calculus to be that of \(\RR^2\) via the local parametrisations. This is the most subtle point of the definition, and historically took a little time to sort out.

Let us deal with the (relatively) simpler notion of continuity before exploring condition 3 further.

#+BEGIN_env defn
A subset \(V \subset S\) is /open/ if and only if \(V = S \cap W\) for an open subset \(W \subseteq \RR^3\).
#+END_env

In the definition of regular surface, we require that each \(\varphi_{\alpha}\) is a homoemorphism; that is, invertible with continuous inverse. This means that for all convergent sequences \((x_n) \subseteq V_{\alpha}\), we have
\[
\lim_{n \to \infty} \varphi_{\alpha}^{-1} (x_n) = \varphi_{\alpha}^{-1} (\lim_{n\to\infty} x_n).
\]

* Examples of Regular Surfaces

#+BEGIN_env eg :title "Graph of a Smooth Function"
The graph \(S = \graph(f)\) of a smooth function is a regular surface. There is just one parametrisation:
\[
\varphi : (u, v) \mapsto (u, v, f(u, v))
\]
The inverse, \(\varphi^{-1} = \pi_{z=0}|_S\) is the projection of \(\RR^3\) onto the \(\lbrace z=0 \rbrace\) hence continuous.

The differential is
\[
d\varphi = \begin{pmatrix}
1 & 0 \\
0 & 1 \\
\partial_u f & \partial_v f
\end{pmatrix}
\]
which is injective.
#+END_env

It's not so hard to show (without topology) that the sphere cannot be globally the graph of any function over any plane.

#+BEGIN_env lem
The sphere is not a graph over any plane \(P \subseteq \RR^3\)
#+END_env

#+BEGIN_env pf
Let \(N\) be the normal to \(P\). Then for any point \(p \in P\), the line \(p + t N\) either intersects in exactly 2 distinct points, 1 point or no points. Substitute: \(p + t N\) into \(x^2 + y^2 + z^2 = 1\) and you get a quadratic in \(t\). Provided \(p + t N\) is not tangent to the sphere (multiplicity $2$ root), the quadratic has either $0$ roots or $2$ roots. Thus if the line intersections non-tangentially, there are two points not in the intersection, but a graph would only have one point.
#+END_env

#+BEGIN_env eg :title "Hemisphere Parametrisation"
#+BEGIN_export html
{% include img.html file="docarmo_cover.jpg" %}
#+END_export

Let \(U = \{u^2 + v^2 < 1\}\) be the unit disc. We can parametrise the "top" and "bottom" of the sphere over the \(z = 0\) plane:
\begin{align*}
\varphi_N (u,v) &= \left(u, v, \sqrt{1 - (u^2 + v^2)}\right) \\
\varphi_S (u,v) &= \left(u, v, -\sqrt{1 - (u^2 + v^2)}\right)
\end{align*}
This covers the sphere minus the equator \(\SS^2 \cap \lbrace z = 0 \rbrace\). To fully cover the sphere with hemispheres requires six such local parametrisations in total. That is, we need also the *E*ast, *W*est, *F*ront, and *B*ack hemispheres:

\begin{align*}
\varphi_E (u, v) &= \left(u, \sqrt{1 - (u^2 + v^2)}, v\right) \\
\varphi_W (u, v) &= \left(u, -\sqrt{1 - (u^2 + v^2)}, v\right) \\
\varphi_F (u, v) &= \left(\sqrt{1 - (u^2 + v^2)}, u, v\right) \\
\varphi_W (u, v) &= \left(-\sqrt{1 - (u^2 + v^2)}, u, v\right)
\end{align*}
#+END_env

#+BEGIN_env eg :title "Spherical Polar Coordinates"
For \((\theta, \phi) \in (0, 2\pi) \times (0, \pi)\), define
\[
\varphi (\theta, \phi) = (\sin \phi \cos \theta, \sin \phi \sin \theta, \cos \phi)
\]

Then \(\varphi\) covers all of the sphere except for the semi-circle \(\{x \geq 0\} \cap \{y = 0\} \cap \SS^2\). We cover the entire sphere by also using the parametrisation
\[
\psi (\theta, \phi) = (\sin \phi \cos \theta, \cos\phi, \sin \phi \sin \theta)
\]
#+END_env


#+BEGIN_env eg :title "Torus"
#+BEGIN_export html
{% include img.html file="torus.png" %}
#+END_export

Start with the \(xz\)-plane circle \((x, y, z) = (a \cos \theta + b, 0, a \sin \theta)\) with \(a < b\). Rotate around the \(z\)-axis to obtain the Torus. The rotation is
\[
(x, z) \mapsto (x \cos \phi, x \sin \phi, z)
\]
Thus our parametrisation is
\[
(a \cos\phi \cos \theta + b \cos\phi, a \sin \phi \cos \theta + b \sin \phi, a \sin \theta).
\]
#+END_env

* Change of Parameters

We define calculus on a regular surface via the local parametrisations. To ensure this calculus is well defined on \(S\), we need to show that it's independent of the choice of local parametrisation. For this we need to relate one local parametrisation to another (at least where they overlap).

#+BEGIN_env defn
Let \(S\) be a regular surface and let \(\varphi_{\alpha} : U_{\alpha} \to V_{\alpha}\), \(\varphi_{\beta} : U_{\beta} \to V_{\beta}\) be local parametrisations. Then /change of parameters/, or /transition map/ from \(\alpha\) to \(\beta\) is the function
\[
\tau_{\alpha\beta} = \varphi_{\beta}^{-1} \circ \varphi_{\alpha} : \varphi_{\alpha}^{-1} (V_{\alpha} \cap V_{\beta}) \to \varphi_{\beta}^{-1} (V_{\alpha} \cap V_{\beta}).
\]
#+END_env

#+BEGIN_export html
{% include img.html file="regular_surface_change_of_params.png" %}
#+END_export

The next theorem is crucial to the development of regular surfaces.

#+BEGIN_env thm
Let \(S\) be a regular surface with local parametrisations
\[
\varphi_{\alpha} : U_{\alpha} \to V_{\alpha} \subseteq S \subseteq \RR^3
\]
Then for each \(\alpha, \beta\) with \(V_{\alpha} \cap V_{\beta} \neq \emptyset\), \(\tau_{\alpha\beta}\) is smooth.

Moreover, \(\tau_{\alpha\beta}\) is invertible with inverse \(\tau_{\beta\alpha}\) hence is a diffeomorphism.
#+END_env

The idea is that \(\tau_{\alpha\beta} = \varphi_{\beta}^{-1} \circ \varphi_{\alpha}\) should be a composition of smooth functions. The problem is we don't know what it means for \(\varphi_{\beta}^{-1}\) to be smooth since it's domain is \(S\) which is in general not a linear space. The solution is to use the regularity condition to show that \(\varphi_{\beta}^{-1} = \Phi_{\beta}^{-1}|_S\) for \(\Phi_{\beta}^{-1} : \RR^3 \to \RR^3\) smooth.

#+BEGIN_env pf
At any fixed point, since \(\varphi_{\beta}\) has injective differential, the two columns of \(d\varphi_{\beta}\) are linearly independent and thus span a plane. Let \(X \in \RR^3\) be any vector not in the span of this plane. We apply the Inverse Function Theorem to the map
\[
\Phi_{\beta} (u, v, w) = \varphi_{\beta} (u, v) + w X,
\]
which extends \(\varphi_{\beta}\) in the sense that
\[
\Phi_{\beta}|_{w=0} = \varphi_{\beta}.
\]
Differentiating,
\begin{equation*}
d\Phi_{\beta} = \begin{pmatrix}
\large{d\varphi} & X
\end{pmatrix}
\end{equation*}
is non-singular (i.e. invertible). By the Inverse Function Theorem, \(\Phi_{\beta}\) is locally a diffeomorphism. Now, \(\Phi_{\beta}|_{w=0} = \varphi\), hence the image of \({w=0}\) under \(\Phi_{\beta}\) is the image of \(\varphi\) which is contained in \(S\). Then \(\Phi_{\beta}^{-1}|_S = \varphi_{\beta}^{-1}\). Hence
\begin{equation*}
\begin{split}
\tau_{\alpha\beta} &= \varphi_{\beta}^{-1} \circ \varphi_{\alpha} \\
&= \Phi_{\beta}^{-1} \circ \varphi_{\alpha}
\end{split}
\end{equation*}
is smooth.
#+END_env

We could in fact replace condition 3 in the definition of regular surface (that \(d\varphi_{\alpha}\) is injective) with the condition that \(\tau_{\alpha\beta}\) is smooth.

#+BEGIN_env ex
Suppose instead of requiring each \(\varphi_{\alpha}\) has injective differential, we require that the transition maps \(\tau_{\alpha\beta} = \varphi_{\beta}^{-1} \circ \alpha\) are smooth for every \(\alpha, \beta\). Show that this implies each \(\varphi_{\alpha}\) has injective differential.
#+END_env

The transition maps are diffeomorphisms between open sets in \(\RR^2\). Define an equivalence relation on all open sets of \(\RR^2\) where \(U \sim V\) if and only if there exists a diffeomorphism \(\tau : U \to V\). The idea is that when it comes to anything to do with calculus, we may consider diffeomorphic sets as the same. In particular, this applies to the overlaps of the transition maps.

#+BEGIN_env ex
Let \(\tau : U \to V\) be a diffeomorphism. Show that
\[
\tau^{\ast} : f \in C^{\infty}(V \to \RR) \mapsto f \circ \tau \in C^{\infty}(U, \RR)
\]
is a bijection.
#+END_env

The map \(\tau_{\beta\alpha}^{\ast}\) establishes a one-to-one correspondence of smooth functions in one parametrisation with smooth functions in another parametrisation. A function \(f : \varphi_{\beta}^{-1} (V_{\alpha}) \to \RR\) is differentiable if and only if \(f \circ \tau_{\alpha\beta} : \varphi_{\alpha}^{-1} (V_{\beta}) \to \RR\) is differentiable.

* Tangent Plane

#+BEGIN_env defn
A /tangent vector/ to a regular surface \(S\) at \(p \in S\) is a vector \(X = \gamma'(0) \in \RR^3\) where
\begin{equation*}
\begin{cases}
\gamma(t) & \in S \\
\gamma(0) &= p \\
\gamma'(0) &= X
\end{cases}
\end{equation*}
for a smooth curve, \(\gamma : (-\delta, \delta) \to \RR^3\).
#+END_env

#+BEGIN_env defn
The /tangent plane/, \(T_p S\) to \(S\) at \(p\) is the set of tangent vectors at \(p\).
#+END_env

Tangent vectors are velocity vectors to curves /along a surface/ and the tangent space is the collection of all such vectors. We expect that since surfaces are two-dimensional, the tangent space should also be two-dimensional; i.e. a plane.

#+BEGIN_export html
{% include img.html file="surface_tangent_plane.png" %}
#+END_export

#+BEGIN_env lem
The tangent plane, \(T_p S = d\varphi_{(u, v)} (\RR^2)\) is a plane in \(\RR^3\) where \(\varphi\) is /any/ local parametrisation with \(\varphi(u, v) = p\).
#+END_env

#+BEGIN_env pf
Let \((u, v) \in \RR^2\) be the unique point such that \(p = \varphi(u, v)\). Given \(V \in \RR^2\), let \(\gamma(t) = \varphi((u, v) + t V)\) so that
\[
d\varphi (V) = \gamma'(0) \in T_p S.
\]
Thus \(d\varphi(\RR^2) \subseteq T_p S\).

Conversely, given \(X = \gamma'(0)\), let
\[
\gamma(t) = \varphi \circ \varphi^{-1} (\gamma(t))
\]
Then
\[
X = \gamma'(0) = d\varphi (\varphi^{-1} \circ \gamma)'(0) \in d\varphi(\RR^2)
\]
Note here that we Use a smooth extension \(\Phi^{-1}\) of \(\varphi^{-1}\) to ensure \(\varphi^{-1} \circ \gamma\) is smooth.

Thus \(T_p S \subseteq d\varphi(\RR^2)\).
#+END_env

Let \(X_1 = \gamma_1'(0)\), \(X_2 = \gamma_2'(0)\) and \(c^1, c^2 \in \RR\). In \(\RR^3\):
\[
c^1 X_1 + c^2 X_2 = \partial_t|_{t=0} \left[p + t(c^1 X_1 + c^2 X_2)\right]
\]
is the velocity vector of a curve, hence a tangent vector - in \(\RR^3\). For a surface \(S\) however, in general, \(p + t(c^1 X_1 + c^2 X_2) \notin S\) and this construction does not work. Instead we proceed as follows: pick any local parametrisation containing \(p\) and let \(U_1, U_2 \in \RR^2\) such that \(d\varphi(U_i) = X_i\). Then using the local parametrisation we may define
\[
c^1 X_1 + c^2 X_2 = d\varphi(c^1 U_1 + c^2 U_2)
\]

#+BEGIN_env ex
Show that \(c^1 X_1 + c^2 X_2\) does not depend on the choice of local parametrisation. /Hint/: use the fact that the transition map is a diffeomorphism.
#+END_env

Using coordinates, we can construct a basis for the tangent space. Note that this construction does depend on the choice of local parameterisation; if we choose a different local parametrisation, we get a different basis for the tangent space. What does not depend on the choice of local parametrisation is the tangent space itself.

First observe that every smooth curve \(\mu : (a, b) \to U\) gives a smooth curve \(\gamma = \varphi \circ \mu : (a, b) \to S\) since
\[
\varphi^{-1} \circ \gamma = \varphi^{-1} \circ \varphi \circ \mu = \mu
\]
is smooth. Thus given a curve \(\mu : (-\epsilon, \epsilon) \to U\) we get a tangent vector \((\varphi \circ \mu)'(0)\) at \(p = \varphi(\mu(0))\).

#+BEGIN_env defn :title "Coordinate Curves and Vectors"
For each \((u, v) \in U\) we define the /coordinate curves/,
\begin{align*}
\gamma_u (t) &= \varphi(u_0 + t, v_0) \\
\gamma_v (t) &= \varphi(u_0, v_0 + t).
\end{align*}
for \(t \in (-\epsilon, \epsilon)\) with \(\epsilon > 0\) sufficiently small so that \(\gamma_u(t), \gamma_t(v) \in U\). Note such an \(\epsilon\) always exists since \(U\) is open so that we may take \(\epsilon > 0\) such that \(B_{\epsilon}(u_0, v_0) \subseteq U\).

The /coordinate tangent vectors/ are
\begin{align*}
e_u &:= \gamma_u'(0) = d\varphi (1, 0) \\
e_v &:= \gamma_v'(0) = d\varphi (0, 1)
\end{align*}
#+END_env

#+BEGIN_env lem
The tangent space \(T_p S\) is spanned by \(\lbrace e_u, e_v \rbrace\).
#+END_env

#+BEGIN_env pf
The vectors \(e_u = d\varphi(1, 0), e_v = d\varphi(0, 1)\) are linearly independent since \(d\varphi\) is injective and \((1, 0), (0, 1)\) are linearly independent. Since \(T_p S\) is \(2\)-dimensional, \(e_u, e_v\) then also span \(T_p S\) and are hence a basis.
#+END_env

#+BEGIN_env eg
Let \(S\) be the unit sphere and let
\begin{equation*}
\begin{split}
\varphi(\theta, \phi) &= (\sin\phi \cos\theta, \sin\phi \sin\theta, \cos\phi) \\
&= (x, y, z)
\end{split}
\end{equation*}
be polar coordinates. Then
\begin{align*}
e_{\theta} &= (-\sin\phi \sin\theta, \sin\phi \cos\theta, 0) \\
&= (-y, x, 0) \\
e_{\phi} &= (\cos\phi \cos\theta, \cos\phi \sin\theta, -\sin\phi) \\
&= \cos\phi (\cos\theta, \sin\theta, 0) - \sin\phi (0, 0, 1) \\
&= \left(\tfrac{xz}{\sqrt{1-z^2}}, \tfrac{yz}{\sqrt{1-z^2}}, -\sqrt{1-z^2}\right)
\end{align*}

In cylindrical coordinates
\[
\varphi(\eta, r) = (\sqrt{1-r^2} \cos\eta, \sqrt{1-r^2} \sin\eta, r)
\]
we have
\begin{align*}
e_{\eta} &= (-\sqrt{1-r^2} \sin \eta, \sqrt{1-r^2} \cos \eta, 0) \\
&= (-y, x, 0) \\
e_r &= \left(\tfrac{-r}{\sqrt{1-r^2}} \cos \eta, \tfrac{-r}{\sqrt{1-r^2}} \sin \eta, 1 \right) \\
&= \left(\tfrac{-xz}{1-z^2}, \tfrac{-yz}{1-z^2}, 1\right)
\end{align*}

The change of basis matrix from \(\lbrace e_{\theta}, e_{\phi} \rbrace\) to \(\lbrace e_{\eta}, e_r \rbrace\) is
\begin{equation*}
\begin{pmatrix}
1 & 0 \\
0 &\tfrac{-1}{\sqrt{1-z^2}}
\end{pmatrix}
\end{equation*}
#+END_env

* Smooth Curves

We begin with smooth curves on a regular surface.

#+BEGIN_env defn
A curve \(\gamma : (a, b) \to S\) is /smooth/ if it is smooth as a map \((a, b) \to \RR^3\).
#+END_env

This definition is what we used when defining tangent vectors, where they were defined as velocity vectors \(\gamma'(0)\) for smooth curves \(\gamma\) in \(\RR^3\) with image contained in \(S\). Using our definition of smooth curve in \(S\), we may now equivalently define tangent vectors as velocity vectors of smooth curves in \(S\).

#+BEGIN_env lem
A curve \(\gamma : (a, b) \to S\) is /smooth/

- *if and only if* for every local parametrisation, \(\varphi_{\alpha}^{-1} \circ \gamma\) is smooth
- *if and only if* there are local parametrisations \(\lbrace \varphi_{\alpha} \rbrace_{\alpha \in A}\) index by a set \(A\) with \(\Img (\gamma) \subseteq \cup_{\alpha \in A} \varphi_{\alpha}(U_{\alpha})\) with \(\varphi_{\alpha}^{-1} \circ \gamma\) smooth for each \(\alpha \in A\).
#+END_env

Note that if \(t \in (a, b)\) such that \(\gamma(t) \notin V_{\alpha} = \varphi_{\alpha}(U_{\alpha})\), then \(\varphi_{\beta}^{-1} \circ \gamma\) is not defined. In this case, by convention we define it to be smooth; another interpretation is that it's vacuously true that \(\varphi_{\beta}^{-1} \circ \gamma\) is smooth at all points where it's defined since there are no points where it's defined!

Note also, the first condition requires that \(\varphi_{\alpha}^{-1} \circ \gamma\) is smooth for *every possible* local parametrisation, while the second only requires this for \(\alpha \in A\). The set \(\lbrace \varphi_{\alpha} \rbrace_{\alpha \in A}\) in the second condition is known as a cover of \(\Img(\gamma)\).

#+BEGIN_env pf
Let us first show the last two condition are equivalent. The first condition implies the second since if \(\varphi_{\alpha}^{-1} \circ \gamma\) is smooth for *every* local parametrisation, then it certainly is true for \(\alpha\) restricted to \(A\).

Conversely, if \(\varphi_{\alpha}^{-1} \circ \gamma\) is smooth for each \(\alpha \in A\), then choose any \(\beta\) (not necessarily in \(A\)) such that \(V_{\beta} \cap \Img(\gamma) \neq \emptyset\) (otherwise \(\varphi_{\beta}^{-1} \circ \gamma\) is not defined and there is nothing to prove). For any \(t \in \gamma^{-1}(V_{\beta})\), choose \(\alpha\) so that \(\gamma(t) \in V_{\alpha}\). Then
\begin{equation*}
\begin{split}
\varphi_{\beta}^{-1} \circ \gamma &= \varphi_{\beta}^{-1} \circ \varphi_{\alpha} \circ \varphi_{\alpha}^{-1} \circ \gamma \\
&= \tau_{\alpha\beta} \circ \varphi_{\alpha}^{-1} \circ \gamma
\end{split}
\end{equation*}
is smooth at \(t\).

Finally, we show that these two (equivalent) conditions are in turn equivalent to the smoothness of \(\gamma\) as a map into \(\RR^3\). If \(\varphi_{\alpha}^{-1} \circ \gamma\) is smooth for all local parametrisations, let \(t \in (a, b)\) and \(\alpha\) such that \(\gamma(t) \in V_{\alpha}\). Then
\[
\gamma(t) = \varphi_{\alpha} \circ (\varphi_{\alpha}^{-1} \circ \gamma) (t)
\]
is smooth at \(t\). Conversely, if \(\gamma\) is smooth into \(\RR^3\), then extend \(\phi_{\alpha}^{-1}\) to a smooth map in which case
\[
\varphi_{\alpha}^{-1} \circ \gamma = \Phi_{\alpha}^{-1} \circ \gamma
\]
is smooth.
#+END_env

* Smooth Maps

Now let us consider smooth maps between surfaces. First we consider the simpler case of smooth maps between a surface and \(\RR^n\).

#+BEGIN_env defn
Let \(S\) be regular surface. \(f : S \to \RR^n\) is /smooth/ if \(f \circ \varphi\) is smooth and \(f : \RR^n \to S\) is smooth if \(\varphi^{-1} \circ f\) is smooth.
#+END_env

Note that the inclusion \(\iota : S \to \RR^3\) is smooth by definition.

#+BEGIN_env defn
Let \(S_1, S_2\) be regular surfaces. \(f : S_1 \to S_2\) is /smooth/ if \(\psi^{-1} \circ f \circ \varphi\) is smooth
\[
\varphi^{-1} \left(f^{-1}(Z) \cap V\right) \subseteq U \subseteq \RR^2 \to W \subseteq \RR^2
\]
for every pair of local parametrisations
\[
\varphi : U \to V \subseteq S, \quad \psi : W \to Z \subset S'
\]
#+END_env

#+BEGIN_env lem
The map \(f : S_1 \to S_2\) is smooth if and only if \(\iota_2 \circ f\) is a smooth map \(S_1 \to \RR^3\).
#+END_env

#+BEGIN_env pf
\[
\iota_2 \circ f = \psi \circ (\psi^{-1} \circ f)
\]
Since \(\psi\) is smooth, the right and side is smooth if and only if the \(\psi^{-1} \circ f\) is smooth.
#+END_env

As expected, composition of smooth function is again smooth.

#+BEGIN_env lem
Let \(g : S_1 \to S_2\), \(f: S_2 \to S_3\) be smooth maps of regular surfaces. Then \(f \circ g\) is smooth.
#+END_env

#+BEGIN_env pf
\[
\varphi_3^{-1} \circ (f \circ g) \circ \varphi_1 = (\varphi_3^{-1} \circ f \circ \varphi_2) \circ (\varphi_2^{-1} \circ g \circ \varphi_1)
\]
#+END_env

#+BEGIN_env eg
Let \(S_1\) be the cylinder \(\lbrace x^2 + y^2 = 1, -1 < z < 1 \rbrace\)

Let \(S_s\) be the sphere \(\lbrace x^2 + y^2 + z^2 = 1 \rbrace\)

\[
f (x, y, z) = (\sqrt{1-z^2} x, \sqrt{1-z^2} y, z)
\]

In cylindrical coordinates for the cylinder and sphere,
\[
f(z, \theta) = (z, \theta)
\]
is certainly smooth!
#+END_env

* The Differential                                                 :noexport:

#+BEGIN_env defn
Let \(f : S_1 \to S_2\) be a smooth map. The differential, \(df_p\) of \(f\) at \(p \in S\) is the linear map
\begin{equation*}
\begin{split}
df_x : T_p S_1 &\to T_{f(p)} S_2 \\
\gamma'(0) &\mapsto (f \circ \gamma)'(0).
\end{split}
\end{equation*}
#+END_env
** The Differential

#+BEGIN_env lem
The differential is well defined.
#+END_env

#+BEGIN_env pf
- \(f \circ \gamma\) is smooth:
  \[
   f \circ \gamma = \iota_2 \circ f \circ \iota_1 \circ \gamma.
   \]

- By the chain rule if \(\gamma'(0) = \sigma'(0)\),
  \[
  df(\gamma'(0)) = df(\sigma'(0))
  \]
#+END_env

** Coordinate Description of Differential

Let \(F(u, v) = \psi^{-1} \circ f \circ \varphi (u, v) = (F_1(u, v), F_2 (u, v))\) with \(p = \varphi(u_0, v_0)\):
\[
df_p = \begin{pmatrix}
\frac{\partial F_1}{\partial u}(v_0, u_0) & \frac{\partial F_1}{\partial v}(v_0, u_0) \\
\frac{\partial F_2}{\partial u}(v_0, u_0) & \frac{\partial F_2}{\partial v}(v_0, u_0)
\end{pmatrix}
\]
** Example

\[
f : \operatorname{Cylinder} \to \SS^2
\]

\[
f(x, y, z) = \left(\sqrt{1-z^2} x, \sqrt{1-z^2} y, z\right)
\]

** Cylindrical Basis For Cylinder

\[
\varphi_C(r, \theta) = (\cos \theta, \sin \theta, r) = (x, y, z)
\]

\begin{equation*}
\begin{split}
e_r &= (0, 0, 1) \\
e_{\theta} &= (-\sin \theta, \cos \theta, 0) = (-y, x, 0)
\end{split}
\end{equation*}

** Cylindrical Basis For Sphere

\begin{equation*}
\begin{split}
\varphi_S (r, \theta) &= (\sqrt{1-r^2} \cos \theta, \sqrt{1-r^2} \sin \theta, r) \\
&= (x, y, z)
\end{split}
\end{equation*}

\begin{equation*}
\begin{split}
e_r &= \left(\tfrac{-r}{\sqrt{1-r^2}} \cos \theta, \tfrac{-r}{\sqrt{1-r^2}} \sin \theta, 1 \right) \\
&= \left(\tfrac{-z}{1-z^2} x, \tfrac{-z}{1-z^2} y, 1\right) \\
e_{\theta} &= (-\sqrt{1-r^2} \sin \theta, \sqrt{1-r^2} \cos \theta, 0) \\
&= (-y, x, 0)
\end{split}
\end{equation*}

** Cylindrical Differential

Since \(\varphi_S^{-1} \circ f \circ \varphi_C = \Id\) in cylindrical coords:
\[
df = \Id!
\]

\[
df(e_r) = e_r \quad df(e_{\theta}) = e_{\theta}
\]

Can directly differentiate
\[
f \circ \varphi_C (r, \theta) = \varphi_S
\]

** Spherical Polar Basis for Sphere

\begin{align*}
\varphi_{\SS^2} (\theta, \phi) &= (\sin\phi \cos\theta, \sin\phi \sin\theta, \cos\phi) \\
&= (x, y, z) \\
e_{\theta} &= (-\sin\phi\sin\theta, \sin\phi\cos\theta, 0) \\
&= (-y, x, 0) \\
e_{\phi} &= (\cos\phi \cos\theta, \cos\phi \sin\theta, -\sin\phi) \\
&= \left(\tfrac{xz}{\sqrt{1-z^2}}, \tfrac{yz}{\sqrt{1-z^2}}, -\sqrt{1-z^2}\right)
\end{align*}

** Cylindrical to Spherical Differential

\begin{align*}
df(e_{\theta}) &= e_{\theta} \\
df(e_r) &= \tfrac{-1}{\sqrt{1-z^2}} e_{\phi}
\end{align*}


