#+OPTIONS: toc:nil num:nil
#+BEGIN_export html
---
title: Surfaces
short_title: Surfaces
---
#+END_export

#+LaTeX_class: article_no_macros
#+LaTeX_Header: \usepackage{pabnotes}
#+LaTeX_Header: \newcommand{\weeknum}{04}
#+LaTeX_Header: \newcommand{\topic}{Surfaces}

#+BEGIN_export html
<ul>
<li><a href="{{ '/slides/surfaces' | relative_url }}" target="_blank">Surfaces Slides</a></li>
<li><a href="{{ '/slides/surface_tangent_space' | relative_url }}" target="_blank">Tangent Space Slides</a></li>
<li><a href="{{ '/pdf/surfaces.pdf' | relative_url }}" target="_blank">Surfaces PDF Notes</a></li>
</ul>
#+END_export

* Graphs

#+BEGIN_env defn
Let \(f : U \subseteq_{\text{open}} \RR^2 \to \RR\) be smooth function. The graph, \(\graph f\) is the set,
\[
\graph f := \{(u, v, f(u, v)) : (u, v) \in U\} \subseteq \RR^3.
\]
#+END_env

The function \(F : U \to \RR^3\) defined by
\[
F(u, v) = (u, v, f(u, v))
\]
is a /parmetrisation/ of \(\graph f\).

Observe that \(F\) gives a one to one identification of the points \((x, y, z) \in \graph f\) with the points \((u, v) \in U\) an open set of \(\RR^2\) on which we can do calculus! As a map \(F : U \to \graph(f)\), the inverse is \(F^{-1} = \pi|_{\graph(f)} : \graph(f) \to U\)
\[
F^{-1} : (x, y, z) \in \graph(f) \mapsto (x, y).
\]

#+BEGIN_env eg :title "Paraboloid"
Consider the paraboloid,
\[
S = \lbrace (x, y, z) : z = x^2 + y^2 \rbrace.
\]
Let \(f (u, v) = u^2 + v^2\) in which case,
\[
\graph(f) = (u, v, u^2 + v^2) = S
\]
and a parametrisation is
\[
F(u, v) = (u, v, u^2 + v^2).
\]
#+END_env

In general, we can't differentiate a function \(\eta : \graph(f) \to \RR\), for if \(p \in \graph(f)\) the definition of derivative gives
\[
\partial_X \eta (p) = \lim_{h \to 0} \frac{\eta(p + hX) - \eta(p)}{h}.
\]
In general \(p + h X \notin \graph{f}\), in which case the difference quotient is not even defined let alone the limit.

For example, let \(p = (1, 0, 1)\) be a point on the paraboloid and let \(X = e_1 = (1, 0, 0)\). Then for any \(h\),
\[
p + hX = (1 + h, 0, 1)
\]
This is not a point on the parabolid \(z = x^2 + y^2\) and hence \(\eta(p + hX)\) is not defined if \(\eta\) is defined only on the graph.

So we need to another way to define smooth functions. We do this via our parametrisation.

#+BEGIN_env defn
A function \(\eta : \graph f \to \RR\) is smooth if the function

\(\eta \circ F (x, y) = \eta(x, y, f(x, y))\) is smooth.

A function \(\eta = (\eta^1, \dots, \eta^m) : \graph f \to \RR^m\) is smooth if each \(\eta^i\) is.
#+END_env

In the case that we start with a smooth function on the ambient space, then restircting to \(\graph(f)\) is smooth. That is, if \(\bar{\eta} : \RR^3 \to \RR\) is smooth then, by the chain rule \(\eta := \bar{\eta}|_{\graph f}\) is smooth since
\[
\eta \circ F = \bar{\eta}\lvert_{\graph f} \circ F = \bar{\eta} \circ F
\]
is the composition of smooth functions.

In fact, all smooth functions arise this way. Here's the local version of that statement.

#+BEGIN_env lem
Let \(\eta : \graph f \to \RR\) be a smooth function. Then /locally/ there exists a smooth function \(\bar{\eta} : \RR^3 \to \RR\) such that \(\eta = \bar{\eta}\lvert_{\graph f}\).
#+END_env

#+BEGIN_env pf :title "Special case - Immersions"
In the special case that \(f \equiv 0\),
\[
F(u, v) = (u, v, 0)
\]
is an inclusion. By assumption \(\eta \circ F (u, v) = \eta(u, v, 0)\) is smooth. Define
\[
\bar{\eta}(x, y, z) = \eta \circ \pi (x, y, z) = \eta(x, y, 0)
\]
which is then smooth.
#+END_env

Thus extending smooth maps on inclusions into coordinate planes is straightforward. The general case follows by the Immersion Theorem which says that a surface is locally a coordinate plane up to diffeomorphism.

#+BEGIN_env pf :title "General Case"
\(F\) is an immersion, hence by the Immersion Theorem there are local diffeomorphisms such that \(F = \psi^{-1} \circ \iota \circ \varphi\). Since \(\psi \circ F = \iota \circ \varphi\) we get that \(\psi(\graph(f)) \subseteq \Img \iota = \lbrace z=0 \rbrace\).

We can (locally) define a new smooth function \(\mu : \lbrace z = 0 \rbrace \to \RR\) by
\[
\mu = \eta \circ \psi^{-1}.
\]
Then
\begin{equation*}
\begin{split}
\eta \circ F &= \eta \circ \psi^{-1} \circ \iota \circ \varphi \\
&= \mu \circ \iota \circ \varphi
\end{split}
\end{equation*}
is smooth since \(\eta \circ F\) is smooth by assumption. Thus
\[
\mu \circ \iota = \eta \circ F \circ \varphi^{-1}
\]
is smooth. Using the fact that \(\iota \circ \pi\) is the identity on \(\{z=0\}\) where \(\pi : \RR^3 \to \RR^2\) is the projection \((x, y, z) \mapsto (x, y)\) we get
\[
\mu = \mu \circ \iota \circ \pi = (\eta \circ F) \circ \varphi^{-1} \circ \pi
\]
is smooth.

Then we let \(\bar{\mu}\) be a smooth extension of \(\mu\) and let
\[
\bar{\eta} = \bar{\mu} \circ \psi^{-1}
\]
which is smooth. Moreover, since \(\bar{\mu}|_{z=0} = \mu\),
\begin{equation*}
\begin{split}
\bar{\eta}|_{\graph(f)} &= (\bar{\mu} \circ \psi^{-1})|_{\graph(f)} \\
&= \bar{\mu}|_{z=0} \circ \psi^{-1}_{\graph(f)} \\
&= (\mu \circ \psi^{-1})|_{\graph(f)} \\
&= \eta
\end{split}
\end{equation*}
and we obtain a local, smooth extension as required.
#+END_env

* Regular Surfaces

Graphs are /global/ surfaces. They are diffeomorphic to an open set in the plane. Many surfaces are not diffeomorphic to an open set in the plane! For example, none of the sphere, torus, cylinder are diffeomorphic to the plane. The proof requires some topology so we won't discuss it here. It's just mentioned to show that the study of regular surfaces requires us to consider more than just graphs - we must widen our definition!

#+BEGIN_env defn
A regular surface, \(S \subseteq \RR^3\) is a set covered by smooth /local parametrisations/ \(\varphi_{\alpha} : U_{\alpha} \subseteq \RR^2 \to \RR^3\) such that

1. \(S = \cup_{\alpha} V_{\alpha}\) where \(V_{\alpha} = \varphi_{\alpha}(U_{\alpha})\) is open in \(S\)
2. \(\varphi_{\alpha}\) is a homeomorphism \(U_{\alpha} \to V_{\alpha}\)
3. \(d\varphi_{\alpha}|_x : \RR^2 \to \RR^3\) is injective for each \(x \in U_{\alpha}\)
#+END_env

#+BEGIN_export html
{% include img.html file="regular_surface.png" %}
#+END_export

We say that a regular surface is /locally/ diffeomorphic to \(\RR^2\). Each of the local parametrisations gives a one-to-one, smooth correspondence of part of \(S\) and an open subset in \(\RR^2\). The first condition in the definition says that every part of \(S\) is in such correspondence. The second condition says that the correspondence is continuous (both ways!) and hence for topological considerations (such as openness, continuity etc.), a regular surface is locally equivalent to \(\RR^2\). Of course, we must at least require the local parametrisations are smooth (we are doing calculus after all). The third condition goes further and the condition that allows us to locally identity \(S\) with an open set in \(\RR^2\) is a *smooth way*. This allows us to define a natural notion of calculus on \(S\), by taking our calculus to be that of \(\RR^2\) via the local parametrisations. This is the most subtle point of the definition, and historically took a little time to sort out.

Let us deal with the (relatively) simpler notion of continuity before exploring condition 3 further.

#+BEGIN_env defn
A subset \(V \subset S\) is /open/ if and only if \(V = S \cap W\) for an open subset \(W \subseteq \RR^3\).
#+END_env

In the definition of regular surface, we require that each \(\varphi_{\alpha}\) is a homoemorphism; that is, invertible with continuous inverse. This means that for all convergent sequences \((x_n) \subseteq V_{\alpha}\), we have
\[
\lim_{n \to \infty} \varphi_{\alpha}^{-1} (x_n) = \varphi_{\alpha}^{-1} (\lim_{n\to\infty} x_n).
\]

* Examples of Regular Surfaces

#+BEGIN_env eg :title "Graph of a Smooth Function"
The graph \(S = \graph(f)\) of a smooth function is a regular surface. There is just one parametrisation:
\[
\varphi : (u, v) \mapsto (u, v, f(u, v))
\]
The inverse, \(\varphi^{-1} = \pi_{z=0}|_S\) is the projection of \(\RR^3\) onto the \(\lbrace z=0 \rbrace\) hence continuous.

The differential is
\[
d\varphi = \begin{pmatrix}
1 & 0 \\
0 & 1 \\
\partial_u f & \partial_v f
\end{pmatrix}
\]
which is injective.
#+END_env

It's not so hard to show (without topology) that the sphere cannot be globally the graph of any function over any plane.

#+BEGIN_env lem
The sphere is not a graph over any plane \(P \subseteq \RR^3\)
#+END_env

#+BEGIN_env pf
Let \(N\) be the normal to \(P\). Then for any point \(p \in P\), the line \(p + t N\) either intersects in exactly 2 distinct points, 1 point or no points. Substitute: \(p + t N\) into \(x^2 + y^2 + z^2 = 1\) and you get a quadratic in \(t\). Provided \(p + t N\) is not tangent to the sphere (multiplicity $2$ root), the quadratic has either $0$ roots or $2$ roots. Thus if the line intersections non-tangentially, there are two points not in the intersection, but a graph would only have one point.
#+END_env

#+BEGIN_env eg :title "Hemisphere Parametrisation"
#+BEGIN_export html
{% include img.html file="docarmo_cover.jpg" %}
#+END_export

Let \(U = \{u^2 + v^2 < 1\}\) be the unit disc. We can parametrise the "top" and "bottom" of the sphere over the \(z = 0\) plane:
\begin{align*}
\varphi_N (u,v) &= \left(u, v, \sqrt{1 - (u^2 + v^2)}\right) \\
\varphi_S (u,v) &= \left(u, v, -\sqrt{1 - (u^2 + v^2)}\right)
\end{align*}
This covers the sphere minus the equator \(\SS^2 \cap \lbrace z = 0 \rbrace\). To fully cover the sphere with hemispheres requires six such local parametrisations in total. That is, we need also the *E*ast, *W*est, *F*ront, and *B*ack hemispheres:

\begin{align*}
\varphi_E (u, v) &= \left(u, \sqrt{1 - (u^2 + v^2)}, v\right) \\
\varphi_W (u, v) &= \left(u, -\sqrt{1 - (u^2 + v^2)}, v\right) \\
\varphi_F (u, v) &= \left(\sqrt{1 - (u^2 + v^2)}, u, v\right) \\
\varphi_W (u, v) &= \left(-\sqrt{1 - (u^2 + v^2)}, u, v\right)
\end{align*}
#+END_env

#+BEGIN_env eg :title "Spherical Polar Coordinates"
For \((\theta, \phi) \in (0, 2\pi) \times (0, \pi)\), define
\[
\varphi (\theta, \phi) = (\sin \phi \cos \theta, \sin \phi \sin \theta, \cos \phi)
\]

Then \(\varphi\) covers all of the sphere except for the semi-circle \(\{x \geq 0\} \cap \{y = 0\} \cap \SS^2\). We cover the entire sphere by also using the parametrisation
\[
\psi (\theta, \phi) = (\sin \phi \cos \theta, \cos\phi, \sin \phi \sin \theta)
\]
#+END_env


#+BEGIN_env eg :title "Torus"
#+BEGIN_export html
{% include img.html file="torus.png" %}
#+END_export

Start with the \(xz\)-plane circle \((x, y, z) = (a \cos \theta + b, 0, a \sin \theta)\) with \(a < b\). Rotate around the \(z\)-axis to obtain the Torus. The rotation is
\[
(x, z) \mapsto (x \cos \phi, x \sin \phi, z)
\]
Thus our parametrisation is
\[
(a \cos\phi \cos \theta + b \cos\phi, a \sin \phi \cos \theta + b \sin \phi, a \sin \theta).
\]
#+END_env

* Tangent Plane                                                    :noexport:

#+BEGIN_env defn
A /tangent vector/ to \(\graph f\) at \(x \in \graph f\) is a vector \(X = \gamma'(0)\in \RR^3\) where \(\gamma(0) = x\).

The /tangent plane/, \(T_x \graph f\) to \(\graph f\) at \(x\) is the set of tangent vectors at \(x\).
#+END_env

Tangent vectors are velocity vectors to curves /along the graph/.

