#+OPTIONS: toc:nil
#+BEGIN_export html
---
title: Calculus Review - Topology
name: calc_review_topology
type: topic
---
#+END_export

#+BEGIN_env defn
Given \(r > 0\) and \(x \in \RR^n\), the /open ball/ of radius \(r\) and centre \(x\) is the set
\[
B_r (x) = \{y \in \RR^n: \abs{x - y} < r\}.
\]

The /closed ball/ of radius \(r\) and centre \(x\) is the set
\[
\bar{B}_r (x) = \{y \in \RR^n: \abs{x - y} \leq r\}.
\]

The /sphere/ of radius \(r\) and centre \(x\) is the set
\[
\SS^{n-1}_r (x) = \{y \in \RR^n: \abs{x - y} = r\}.
\]
#+END_env

#+BEGIN_env defn
For \(x, y \in \RR^n\), the distance \(\abs{x - y}\) is defined to be
\[
\abs{x - y} = \sqrt{(x^1 - y^1)^2 + \cdots + (x^n - y^n)^2}
\]
where \(x = (x^1, \dots, x^n)\) and \(y = (y^1, \dots, y^n)\).
#+END_env

- The open ball is the set of points of distance to \(x\) strictly less than \(r\).
- The closed ball is the set of points of distance to \(x\) less than or equal to \(r\).
- The sphere is the set of points of distance to \(x\) equal to \(r\).

It is sometimes said that analysis is simply applications of the triangle inequality:
\[
\abs{x - y} \leq \abs{x - z} + \abs{z - y}.
\]

#+BEGIN_env defn
A set \(U \subset \RR^n\) is said to be /open/ provided for every \(x \in U\), there exists an \(r = r(x)\) such that
\[
B_r(x) \subseteq U.
\]


A set \(C\) is /closed/ if it's complement,
\[
\RR^n \backslash C := \{y \in \RR^n : y \notin C\}
\]
is open.
#+END_env


- By this definition, open balls are open, closed balls are closed and spheres are closed.
- Given any point of an open set, we can always move /uniformly/ a little in any direction and remain in the open set.

#+BEGIN_env defn
A set \(S \subseteq \RR^n\) is /bounded/ if there exists an \(x \in \RR^n\) and an \(r > 0\) such that \(S \subseteq B_r(x)\).

A set \(K \subseteq \RR^n\) is /compact/ if it is closed and bounded.
#+END_env

- \(S \subseteq \RR^n\) is bounded iff for every \(x \in \RR^n\) there exists an \(r = r(x)\) such that \(S \subseteq B_r(x)\).
- A set \(K \subseteq \RR^n\) is compact if and only if for every /open cover/ \(\{U_{\alpha}\}\), there exists a /finite subcover/.
  - An /open cover/ is a collection of open sets \(\{U_{\alpha}\}\) such that \(K \subseteq \cup_{\alpha} U_{\alpha}\).
  - A /finite subcover/ is a cover by finitely many \(U_{\alpha_1}, \cdots, U_{\alpha_N}\)
  - Equivalent for \(\RR^n\).
