#+OPTIONS: toc:nil
#+BEGIN_export html
---
title: Immersion and Submersion Theorems
name: ift_immersion_submersion
type: topic
---
#+END_export

Here are some further statements equivalent to the Inverse Function Theorem, and hence also equivalent to the Implicit Function Theorem.

#+BEGIN_env ex
Prove that the theorems below are equivalent to the Inverse Function Theorem. You may find it easier to prove equivalence with the Implicit Function Theorem which is equivalent anyway.
#+END_env

#+BEGIN_env defn
Let \(F : \RR^{n+k} \to \RR^{k}\) be a smooth map. Then \(F\) is an /submersion/ if \(dF\) is surjective.
#+END_env

Note that
\begin{equation*}
\begin{split}
dF \text{ surjective} & \Leftrightarrow dF \text{ has maximal rank} \\
& \Leftrightarrow \operatorname{rnk} dF = k = \operatorname{dim} \operatorname{coDom} (dF) \\
& \Leftrightarrow \operatorname{dim} \ker dF = n
\end{split}
\end{equation*}

#+BEGIN_env defn
An projection of \(\RR^{n+k}\) onto \(\RR^k\) is a map of the form
\[
\pi: x \in \RR^{n+k} \mapsto (x^{n+1}, \dots, x^{n+k}) \in \RR^k
\]
#+END_env

Note that \(d\pi = \begin{pmatrix} \operatorname{Id}_n & 0_k \end{pmatrix}\) is surjective.

We may also change the order: eg. \(\pi(x_1, x_2, x_3) = (x_2, x_3)\)

#+BEGIN_env thm
Let \(F\) be a submersion. Then \(F\) is locally a projection up to diffeomorphism.
#+END_env

There are diffeomorphisms
\begin{align*}
\varphi & : U \subseteq \RR^{n+k} \to V \subseteq \RR^{n+k} \\
\psi & : W \subseteq \RR^k \to Z \subseteq \RR^k \\
\end{align*}
such that \(F|_U = \psi^{-1} \circ \pi \circ \varphi\)

Dual to the notion of submersion is the notion of immersion.

#+BEGIN_env defn
Let \(F : \RR^n \to \RR^{n+k}\) be a smooth map. Then \(F\) is an /immersion/ if \(dF\) is injective.
#+END_env

\begin{equation*}
\begin{split}
dF \text{ injective} & \Leftrightarrow dF \text{ has maximal rank} \\
& \Leftrightarrow \operatorname{rnk} dF = n = \operatorname{dim} \operatorname{Dom} (dF) \\
& \Leftrightarrow \operatorname{dim} \ker dF = 0
\end{split}
\end{equation*}

#+BEGIN_env defn
An inclusion of \(\RR^n\) into \(\RR^{n+k}\) is a map of the form
\[
\iota: x \in \RR^n \mapsto (x, 0_k)
\]
where \(0_k = (0, \dots, 0) \in \RR^k\).
#+END_env

Note that \(d\iota = \begin{pmatrix} \operatorname{Id}_n \\ 0_k \end{pmatrix}\) is injective.

We may also change the order: eg. \(\iota(x_1, x_2) = (0, x_1, x_2, 0)\)

#+BEGIN_env thm
Let \(F\) be an immersion. Then \(F\) is locally an inclusion up to diffeomorphism.
#+END_env

There are diffeomorphisms
\begin{align*}
\varphi & : U \subseteq \RR^n \to V \subseteq \RR^n \\
\psi & : W \subseteq \RR^{n+k} \to Z \subseteq \RR^{n+k} \\
\end{align*}
such that \(F|_U = \psi^{-1} \circ \iota \circ \varphi\)
