#+OPTIONS: toc:nil
#+BEGIN_export html
---
title: Inverse Function Theorem Proof
name: ift_proof
type: topic
---
#+END_export


#+BEGIN_env thm
Let \(f : \RR^n \to \RR^n\) a smooth function such that \(df_{x_0}\) is invertible at \(x_0\). Then there is an open set \(U\) containing \(x_0\) and an open set \(V\) containing \(f(x_0)\) such that \(f|_U : U \to V\) is a diffeomorphism. Moreover
\[
df^{-1}_{f(x_0)} = (df_{x_0})^{-1}
\]
#+END_env

The strategy of proof is as follows: Define \(T_y (x) = x - df_{x_0}^{-1} (f(x) - y)\). Then we have two steps.

- Step 1 :: \(T_y\) is a contraction \(T_y : \bar{B}_r(x_0) \to \bar{B}_r(x_0)\)
- Step 2 :: Prove \(f^{-1}\) is smooth.

We will actually break up each step into smaller lemmas.

#+BEGIN_env lem
For each fixed \(y\) sufficiently close to \(y_0 = F(x_0)\),
\[
T_y (x) = x - df_{x_0}^{-1} (f(x) - y)
\]
is a contraction map.
#+END_env

#+BEGIN_env pf
\[
dT_{x_0} = d\Id_{x_0} - df_{x_0}^{-1} df_{x_0} = 0.
\]

Continuity of \(dT\) gives an open neighbourhood \(U\) of \(x_0\) such that \(\|dT_{x_0}\| \leq 1/2\):
\[
\abs{dT_{x} \cdot X} \leq \frac{1}{2} \abs{X}.
\]

From \(\abs{dT_{x} \cdot X} \leq \frac{1}{2} \abs{X}\) and the mean value inequality,
\[
\abs{T(x_1) - T(x_2)} \leq \frac{1}{2}\abs{x_1 - x_2}
\]
so that \(T\) is /contractive/ for \(x_1, x_2 \in U\).
#+END_env

In order to conclude that \(T\) has a unique fixed point, we need to verify that there is an \(r > 0\) such that \(T : \bar{B}_r(x_0) \to \bar{B}_r(x_0)\). Since \(x_0 \in U\) and \(U\) is open, there exists an \(r > 0\) such that \(B_r(x_0) \subseteq U\).

#+BEGIN_env lem
Let \(y_0 = f(x_0)\) and \(y \in B_s(y_0)\) with \(s\) any number satisfying
\[
0 < s < \frac{1-L}{\|df_{x_0}^{-1}\|} r.
\]
Then for any \(y \in B_s(y_0)\), \(T_y\) maps \(\bar{B}_r(x_0)\) to itself.
#+END_env

#+BEGIN_env pf
For \(x \in B_r(x_0)\), recalling \(T(x) = x - df_{x_0}^{-1}(f(x) - y)\) we have
\begin{align*}
\abs{T(x) - x_0} &\leq \abs{T(x) - T(x_0)} + \abs{T(x_0) - x_0} \\
&\leq L\abs{x-x_0} + \abs{-df_{x_0}^{-1}(f(x_0) - y)} \\
&\leq L\abs{x-x_0} + \|df_{x_0}^{-1}\| \abs{y_0 - y} \\
&\leq r L + \|df_{x_0}^{-1}\|s \\
&\leq r L + (1-L)r = r.
\end{align*}
#+END_env

Let us state explicitly what the previous lemmas give us.

#+BEGIN_env lem
For each \(y \in \bar{B}_s(y_0)\), there exists a unique fixed point \(x^{\ast}_y \in \bar{B}_r (x_0)\) for \(T_y\) and hence \(f\) restricted to \(f^{-1}(B_s(y_0) \cap B_r(x_0)\) is invertible.
#+END_env

#+BEGIN_env pf
For each \(y \in B_s(y_0)\), \(T_y : \bar{B}_r (x_0) \to \bar{B}_r (x_0)\) is a contraction mapping hence has a unique fixed point \(x^{\ast}_y\):
\[
x^{\ast}_y = T_y(x^{\ast}_y) = x^{\ast}_y - df_{x_0}^{-1} (f(x^{\ast}_y) - y).
\]
Cancelling \(x^{\ast}_y\) from both sides and using the fact that \(df_{x_0}^{-1}\) is non-singular:
\begin{equation*}
\begin{split}
x^{\ast}_y = T_y(x^{\ast}_y) &\Leftrightarrow df_{x_0}^{-1} (f(x^{\ast}_y) - y) = 0 \\
&\Leftrightarrow f(x^{\ast}_y) = y
\end{split}
\end{equation*}
Thus the unique fixed point \(x^{\ast}_y\) is also the unique solution of \(f(x) = y)\) for \(x \in B_r(x_0)\) provided \(f(x^{\ast}_y \in B_s(y_0)\) and we may define
\[
f^{-1} (y) = x^{\ast}_y.
\]
Note we need to restrict the range of \(x\) to the open set \(f^{-1}(B_s(y_0)) \cap B_r(x_0)\) so that \(f\) maps this set into \(B_s(y_0)\).
#+END_env

Now we move onto step 2, which we also prove by a series of lemmas.

#+BEGIN_env lem
The (local) inverse \(f^{-1}\) is continuous.
#+END_env

#+BEGIN_env pf
\begin{equation*}
\begin{split}
\abs{x_1 - x_2 - df_{x_0}^{-1}(f(x_1) - f(x_2))} &= \abs{T(x_1) - T(x_2)} \\
&\leq L \abs{x_1 - x_2}.
\end{split}
\end{equation*}
By the /reverse triangle inequality/
\[
\abs{x_1 - x_2} - \abs{df_{x_0}^{-1}(f(x_1) - f(x_2))} \leq L \abs{x_1 - x_2}.
\]
Thus
\begin{equation*}
\begin{split}
\abs{x_1 - x_2} &\leq \frac{\abs{df_{x_0}^{-1}(f(x_1) - f(x_2))}}{1 - L} \\
&\leq \frac{\|df_{x_0}^{-1}\|}{1 - L} \abs{f(x_1) - f(x_2)}.
\end{split}
\end{equation*}
Letting \(y_i = f(x_i)\) so that \(x_i = f^{-1}(y_i)\) gives continuity (even Lipschitz):
\[
\abs{f^{-1}(y_1) - f^{-1}(y_2)} \leq \frac{\|df_{x_0}^{-1}\|}{1 - L}\abs{y_1 - y_2}.
\]
#+END_env

#+BEGIN_env lem
The (local) inverse \(f^{-1}\) is differentiable.
#+END_env

#+BEGIN_env pf
Pick any arbitrary \(y \in B_s(y_0)\) and any \(h\) such that \(y + h \in B_s(y_0)\), say \(h \in B_{\epsilon} (0)\) so that \(y + h \in B_{\epsilon} (y) \subseteq B_s(y_0)\).

Let \(x = f^{-1} (y)\) and define
\[
R = f^{-1} (y + h) - f^{-1} (y) - df_{x}^{-1} \cdot h.
\]

We need to show that
\[
\lim_{h\to 0} \frac{\abs{R}}{\abs{h}} = 0.
\]
Let \(k = f^{-1}(y + h) - f^{-1} (y)\) so that \(h = f(x + k) - f(x)\). Then
\begin{align*}
R &= f^{-1} (y + h) - f^{-1} (y) - df_{x}^{-1} \cdot h \\
&= k - df_x^{-1} (f(x + k) - f(x)) \\
&= k - df_x^{-1}(df_x k + \omicron(k)) \\
&= -df_x^{-1} (\omicron(k)).
\end{align*}
Since \(f^{-1}\) is Lipschitz, with constant \(M\) say, we have
\[
\abs{k} = \abs{f^{-1}(y + h) - f^{-1}(y)} \leq M \abs{y + h - y} = M \abs{h}.
\]
\[
\frac{\abs{R}}{\abs{h}} \leq \|df_x^{-1}\| \frac{\omicron(k)}{\abs{h}} \leq M \|df_x^{-1}\| \frac{\omicron(k)}{\abs{k}}.
\]
The right hand side goes to zero as \(h \to 0\) since \(\abs{k} \leq M \abs{h}\) implies \(k \to 0\) and then by definition of \(\omicron(k)\).
#+END_env

#+BEGIN_env lem
The (local) inverse, \(f^{-1}\) is smooth.
#+END_env

#+BEGIN_env pf
We have shown the existence of a differentiable local inverse \(f^{-1}\) to \(f\) with differential
\[
d(f^{-1})_y = (df_x)^{-1}
\]
where \(x = f^{-1}(y)\).

Now, by Cramers's rule, given an invertible matrix \(A\), the inverse is
\[
A^{-1} = \frac{1}{\det A} \operatorname{adj} A
\]
where the \(\operatorname{adj} A\) is the /adjugate matrix/ formed from cofactors of \(A\) - that is the determinants of the minors of \(A\). As a function then, \(A \mapsto A^{-1}\) we see that the components are rational functions of the entries of \(A\) (since determinants are polynomials in the entries of \(A\)). The inverse function \(\operatorname{Inv}\) is smooth function from the open set of non-singular matrices (\(\det A \ne 0\)) to itself.

Then since \(x \mapsto df_x\) is smooth,
\[
y \mapsto df^{-1}_y = (df_{f^{-1}(y)})^{-1} = \operatorname{Inv} \circ df \circ f^{-1} (y)
\]
is a composition of \(C^0\) functions hence \(C^0\). Then \(f^{-1}\) is \(C^1\).

Now
\[
df^{-1}_y = \operatorname{Inv} \circ df \circ f^{-1} (y)
\]
and \(df^{-1}\) is the composition of \(C^1\) functions hence is also \(C^1\).

That is \(f^{-1}\) is \(C^2\). By induction, \(f^{-1}\) is \(C^k\) for any \(k\) and hence smooth.
#+END_env
