#+TITLE: Inverse Function Theorem
#+OPTIONS: toc:nil num:nil

* Inverse Function Theorem
** \(1D\) Inverse Function Theorem

#+BEGIN_env thm
Let \(f : \RR \to \RR\) be a smooth function with \(f'(x_0) \ne 0\), there exists an interval \(I\) containing \(x_0\) and an interval \(J\) containing \(f(x_0)\) so that \(f : I \to J\) is a diffeomorphism.
#+END_env

** Inverse Function Theorem

#+BEGIN_env thm
Let \(f : \RR^n \to \RR^n\) a smooth function such that \(df_{x_0}\) is invertible at \(x_0\). Then there is an open set \(U\) containing \(x_0\) and an open set \(V\) containing \(f(x_0)\) such that \(f|_U : U \to V\) is a diffeomorphism. Moreover
\[
df^{-1}_{f(x_0)} = (df_{x_0})^{-1}
\]
#+END_env

** IFT: Chain Rule

If \(f\) is a diffeomorphism, then \(f^{-1} \circ f (x) = x\). That is, \(f^{-1} \circ f = \Id_x\).

Since \(d\Id_x = \Id_n\), by the chain rule we have
\[
\Id_n = d\Id_x = d(f^{-1} \circ f)_{x_0} = df^{-1}_{f(x_0)} \cdot df_{x_0}.
\]

That is \(df_{x_0}\) is invertible and
\[
(df_{x_0})^{-1} = df^{-1}_{f(x_0)}.
\]

** IFT: Idea

\[
f(x) = f(x_0) + df_{x_0} \cdot (x - x_0) + \omicron(|x-x_0|).
\]

Ignoring \(\omicron(|x-x_0|)\):
\[
f(x) = f(x_0) + df_{x_0} \cdot (x - x_0)
\]

\[
x = x_0 + df_{x_0}^{-1} (f(x) - f(x_0)).
\]

\[
f^{-1}(y) = f^{-1}(y_0) + df_{x_0}^{-1} \cdot (y - y_0).
\]

** IFT: Contraction

To prove the Inverse Function Theorem, given \(y\) we uniquely solve \(f(x) = y\) by defining

\[
T_y (x) = x - df_{x_0}^{-1} (f(x) - y).
\]

and show that for suitable \(r > 0\), \(T_y\) is a contraction map \(\bar{B}_r(x_0) \to \bar{B}_r(x_0)\).

* IFT: Example
** IFT: Example

\begin{equation*}
\begin{cases}
x - y^2 &= a \\
x^2 + y + y^3 &= b
\end{cases}
\end{equation*}

For \((a, b) = (0, 0)\): \((x, y) = (0, 0)\) is a solution.

*Question*: For what \((a, b)\) is the system solvable?

** IFT: Example

Let \(F(x, y) = (x - y^2, x^2 + y - y^3)\)

\begin{equation*}
dF = \begin{pmatrix}
1 & -2y \\
2x & 1 - 3y^2
\end{pmatrix}
\end{equation*}

The \(dF_{(0, 0)} = \operatorname{Id}\) hence by the IFT there is a neighbourhood of \((x, y) = (0, 0)\) for which \(F\) maps diffeomorphically onto a neighbourhood of \((a, b) = (0, 0)\) hence there is a unique solution for \((a, b)\) in a neighbourhood of \((0, 0)\).

* Implicit Function Theorem
** Implicit Function Theorem

For \((x, y) \in \RR^n \oplus \RR^k \simeq \RR^{n+k}\) we write
\begin{equation*}
dF = \begin{pmatrix} d_x F & d_y F \end{pmatrix}
\end{equation*}

#+BEGIN_env thm
Let \(F : \RR^{n+k} \to \RR^k\) be smooth with \((x_0, y_0)\) such that \(d_y F|_{(x_0, y_0)}\) is invertible. Then there is an open neighbourhood \(U\) of \(x_0\) and a unique smooth function \(g : U \to \RR^n\) such that
\[
F(x, g(x)) = F(x_0, y_0).
\]
#+END_env

** Proof

Define
\[
\bar{F}(x, y) = (x, F(x, y)) \in \RR^{n+k}
\]

\begin{equation*}
d\bar{F} = \begin{pmatrix}
\operatorname{Id}_n & 0 \\
d_x F & d_y F
\end{pmatrix}
\end{equation*}

** Proof

\(d\bar{F}\) is invertible, hence by the inverse function theorem, \(\bar{F}\) is locally invertible.

Since \(\bar{F}(x, y) = (x, F(x, y))\),
\[
\bar{F}^{-1}(x, y) = (x, G(x, y))
\]

Letting \(c = F(x_0,y_0)\),
\[
g(x) = G(x, c)
\]

** Interpretation

Consider the level set

\[
F^{-1}(c) = \lbrace (x, y) : F(x, y) = c \rbrace.
\]

If \(d_y F\) is invertible for each \((x, y) \in F^{-1}(c)\), then the level set is locally the graph of a smooth function.

** Unit Circle

#+BEGIN_env eg
Let \(F(x, y) = x^2 + y^2\)

Here \(n=k=1\)

\begin{equation*}
dF = \begin{pmatrix} 2x & 2y \end{pmatrix}
\end{equation*}

For \(x \neq \pm 1\)
\[
F(x, \sqrt{1-x^2}) = 1
\]
#+END_env

* Submersion Theorem
** Submersions

#+BEGIN_env defn
Let \(F : \RR^{n+k} \to \RR^{k}\) be a smooth map. Then \(F\) is a /submersion/ if \(dF\) is surjective.
#+END_env

\begin{equation*}
\begin{split}
dF \text{ surjective} & \Leftrightarrow \text{Maximal Rank} \\
& \Leftrightarrow \operatorname{rnk} dF = k = \operatorname{dim} \operatorname{coDom} (dF) \\
& \Leftrightarrow \operatorname{dim} \ker dF = n
\end{split}
\end{equation*}

** Projections

An projection of \(\RR^{n+k}\) onto \(\RR^k\) is a map of the form
\[
\pi: x \in \RR^{n+k} \mapsto (x^{n+1}, \dots, x^{n+k}) \in \RR^k
\]

Note that \(d\pi = \begin{pmatrix} 0 & \operatorname{Id}_k \end{pmatrix}\) is surjective.

We may also change the order: eg. \(\pi(x_1, x_2, x_3) = (x_2, x_3)\)

** Sumbersion Theorem

#+BEGIN_env thm
Let \(F\) be a submersion. Then \(F\) is locally a projection up to diffeomorphism.
#+END_env

There are diffeomorphisms
\begin{align*}
\varphi & : U \subseteq \RR^{n+k} \to V \subseteq \RR^{n+k} \\
\psi & : W \subseteq \RR^k \to Z \subseteq \RR^k \\
\end{align*}
such that \(F|_U = \psi^{-1} \circ \pi \circ \varphi\)

* Immersion Theorems
** Immersions

#+BEGIN_env defn
Let \(F : \RR^n \to \RR^{n+k}\) be a smooth map. Then \(F\) is an /immersion/ if \(dF\) is injective.
#+END_env

\begin{equation*}
\begin{split}
dF \text{ injective} & \Leftrightarrow \text{Maximal Rank} \\
& \Leftrightarrow \operatorname{rnk} dF = n = \operatorname{dim} \operatorname{Dom} (dF) \\
& \Leftrightarrow \operatorname{dim} \ker dF = 0
\end{split}
\end{equation*}

** Inclusions

An inclusion of \(\RR^n\) into \(\RR^{n+k}\) is a map of the form
\[
\iota: x \in \RR^n \mapsto (x, 0_k)
\]
where \(0_k = (0, \dots, 0) \in \RR^k\).

Note that \(d\iota = \begin{pmatrix} \operatorname{Id}_n \\ 0_k \end{pmatrix}\) is injective.

We may also change the order: eg. \(\iota(x_1, x_2) = (0, x_1, x_2, 0)\)

** Immersion Theorem

#+BEGIN_env thm
Let \(F\) be an immersion. Then \(F\) is locally an inclusion up to diffeomorphism.
#+END_env

There are diffeomorphisms
\begin{align*}
\varphi & : U \subseteq \RR^n \to V \subseteq \RR^n \\
\psi & : W \subseteq \RR^{n+k} \to Z \subseteq \RR^{n+k} \\
\end{align*}
such that \(F|_U = \psi^{-1} \circ \iota \circ \varphi\)
